services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-gateway:
    build: ./api_gateway
    ports:
      - '3000:3000'
    depends_on:
      - user-service
      - auth-service

  user-service:
    build: ./services/microservice-user
    ports:
      - '3002:3002'
    depends_on:
      - postgres

  auth-service:
    build: ./services/microservice-auth
    ports:
      - '3001:3001'
    depends_on:
      - user-service
