services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minombre2
      POSTGRES_DB: proyecto_web_movil
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  user-service:
    build: ./services/microservice-users
    ports:
      - '3002:3002'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: minombre2
      DB_NAME: proyecto_web_movil
    depends_on:
      - postgres
    entrypoint:
      [
        'sh',
        '-c',
        'until nc -z postgres 5432; do echo "Esperando PostgreSQL..."; sleep 1; done; yarn start:prod',
      ]

  auth-service:
    build: ./services/microservice-auth
    ports:
      - '3001:3001'
    environment:
      USER_SERVICE_URL: http://user-service:3002
    depends_on:
      - user-service
    entrypoint:
      [
        'sh',
        '-c',
        'until nc -z postgres 5432; do echo "Esperando PostgreSQL..."; sleep 1; done; yarn start:prod',
      ]

  api-gateway:
    build: ./api_gateway
    ports:
      - '3003:3003'
    depends_on:
      - auth-service
      - user-service

volumes:
  postgres_data:
